name: Pull request
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - develop
      - "feature/**"

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.0
          bundler-cache: true

      - name: Test - Fastlane tests
        run: bundle exec fastlane test
